#!/bin/bash

# Forked from benkulbertis/cloudflare-update-record.sh
# CHANGE THESE

# Global API Key (Deprecated + Dangerous)
# Note: Please be caution as the Global API key can have unlimited access to **all** domain and features in your account.
auth_email="john.appleseed@example.org"            # The email used to login 'https://dash.cloudflare.com'
auth_key="f1nd7h47fuck1n6k3y1ncl0udfl4r3c0n50l3"   # Top right corner, "My profile" > "Global API Key"

# API Token (Recommended)
#####                                                                             #####
# WARNING: If you put any value inside the API Token variable,                        #
#            the script will automatically use the token and omit the Global API key, #
#            regardless if the Global API key is defined or not.                      #
#####                                                                             #####
auth_token="xxxx-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# Domain and DNS record for synchronization
zone_identifier="f1nd7h3fuck1n6z0n31d3n71f13r4l50" # Can be found in the "Overview" tab of your domain
record_name="dualstack.example.org"                # Which record you want to be synced

# DO NOT CHANGE LINES BELOW

# SCRIPT START
echo -e "Check Initiated"

# Check for current external network IP
ip4=$(curl -s4 https://icanhazip.com/)
ip6=$(curl -s6 https://icanhazip.com/)
if [[ ! -z "${ip4}" && ! -z "${ip6}" ]]; then
  echo -e "  > Fetched current external network IPv4 address: ${ip4}"
  echo -e "  > Fetched current external network IPv6 address: ${ip6}"
else
  >&2 echo -e "Network error, cannot fetch external network IP."
fi

# The execution of update
if [[ ! -z "${auth_token}" ]]; then
  header_auth_paramheader=( -H '"Authorization: Bearer '${auth_token}'"' )
else
  header_auth_paramheader=( -H '"X-Auth-Email: '${auth_email}'"' -H '"X-Auth-Key: '${auth_key}'"' )
fi

# Seek for the record
seek_current_dns_value_cmd=( curl -s -X GET "https://api.cloudflare.com/client/v4/zones/${zone_identifier}/dns_records?name=${record_name}&type=._._seek_dns_type_._." "${header_auth_paramheader[@]}" -H '"Content-Type: application/json"' )
record4="${seek_current_dns_value_cmd//._._seek_dns_type_._./A}"
record6="${seek_current_dns_value_cmd//._._seek_dns_type_._./AAAA}"

# Can't do anything without both record
if [[ "${record4}" == *'"count":0'* || "${record6}" == *'"count\":0'* ]]; then
  >&2 echo -e "[Cloudflare DDNS] Dual stack records do not exist, perhaps create them first?"
  exit 1
fi

# Set existing IP address from the fetched record
old_ip4=$(echo "${record4}" | sed 's/.*"content":"//;s/".*//')
old_ip6=$(echo "${record6}" | sed 's/.*"content":"//;s/".*//')

# Compare either one is the same
# NOTE: The script will update even one IP remains the same.
if [[ "${ip4}" == "${old_ip4}" && "${ip6}" == "${old_ip6}" ]]; then
  echo "[Cloudflare DDNS] IPs have not changed."
  exit 0
fi

# Set the record identifier from result
record4_identifier=$(echo "${record4}" | sed 's/.*"id":"//;s/".*//')
record6_identifier=$(echo "${record6}" | sed 's/.*"id":"//;s/".*//')

# The secret sause for executing the update
json_data_v4="'"'{"id":"'${zone_identifier}'","type":"A","proxied":false,"name":"'${record_name}'","content":"'${ip4}'","ttl":120}'"'"
json_data_v6="'"'{"id":"'${zone_identifier}'","type":"AAAA","proxied":false,"name":"'${record_name}'","content":"'${ip6}'","ttl":120}'"'"
update_cmd=( curl -s -X PUT '"https://api.cloudflare.com/client/v4/zones/'${zone_identifier}'/dns_records/'${record4_identifier}'"' "${header_auth_paramheader[@]}" -H '"Content-Type: application/json"' )

# Execution result
update4="${update_cmd[@]}" --data "$json_data_v4"
update6="${update_cmd[@]}" --data "$json_data_v6"

# The moment of truth
if [[ "${update4}" == *'"success":false'* || "${update6}" == *'"success":false'* ]]; then
  >&2 echo -e "[Cloudflare DDNS] Update failed for '${record4_identifier}' and '${record6_identifier}'.\n\nDUMPING RESULTS:\n${update4}\n\n${update6}"
  exit 1
else
  echo "[Cloudflare DDNS] IPv4 address '${ip4}' and IPv6 address '${ip6}' has been synced to Cloudflare."
fi
